import Head from 'next/head'
import Hero from '../components/Hero'
import Category from '../components/Category'
import Service from '../components/Service'
import Taste from '../components/Taste'
import HotPizza from '../components/HotPizza'
import Testimonial from '../components/Testimonial'
import Popular from '../components/Popular'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Food For You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Category/>
      <Service/>
      <Popular/>
      <Taste/>
      <HotPizza/>
      <Testimonial/>
    </div>
  )
}
